import type { WorkspaceData } from './types';

export const seedWorkspace: WorkspaceData = {
  subjects: [
    {
      id: 'design',
      name: 'Design systems',
      detail: 'Visual foundations & product thinking',
      short: 'DS',
      color: '#B896FF',
      accent: 'lavender',
      deadline: '2026-10-26',
      icon: '✦',
      pinned: true,
      lectures: [
        {
          id: 'l-design-1',
          title: 'Typography systems',
          url: 'https://www.youtube.com/watch?v=K8YELRmUb5o',
          duration: '34 min',
          channel: 'Design Course',
          status: 'in_progress',
          favorite: true,
          bookmarked: true,
          tags: ['typography', 'foundation'],
          note: 'Review type scale decisions and **line-height**.',
        },
        {
          id: 'l-design-2',
          title: 'Components that scale',
          url: 'https://www.youtube.com/watch?v=Z0O9U4x5dK8',
          duration: '42 min',
          channel: 'Design Course',
          status: 'completed',
          favorite: false,
          bookmarked: false,
          tags: ['components'],
          note: '',
        },
        {
          id: 'l-design-3',
          title: 'Card states and feedback',
          url: 'https://www.youtube.com/watch?v=8XcknFXDHgc',
          duration: '21 min',
          channel: 'Mizko',
          status: 'not_started',
          favorite: false,
          bookmarked: false,
          tags: ['ui'],
          note: '',
        },
      ],
    },
    {
      id: 'ml',
      name: 'Machine learning',
      detail: 'Practical foundations',
      short: 'ML',
      color: '#F7C879',
      accent: 'peach',
      deadline: '2026-11-08',
      icon: '⌁',
      pinned: false,
      lectures: [
        {
          id: 'l-ml-1',
          title: 'Gradient descent',
          url: 'https://www.youtube.com/watch?v=sDv4f4s2SB8',
          duration: '50 min',
          channel: 'StatQuest',
          status: 'not_started',
          favorite: true,
          bookmarked: false,
          tags: ['math'],
          note: '',
        },
        {
          id: 'l-ml-2',
          title: 'Classification basics',
          url: 'https://www.youtube.com/watch?v=JcI5Vnw0b2c',
          duration: '28 min',
          channel: 'StatQuest',
          status: 'completed',
          favorite: false,
          bookmarked: false,
          tags: ['classification'],
          note: '',
        },
      ],
    },
    {
      id: 'spanish',
      name: 'Spanish essentials',
      detail: 'Daily practice routine',
      short: 'SE',
      color: '#73D4C1',
      accent: 'mint',
      deadline: '2026-12-01',
      icon: '◌',
      pinned: false,
      lectures: [
        {
          id: 'l-es-1',
          title: 'Verb practice',
          url: 'https://www.youtube.com/watch?v=OQ6JzhKMgC0',
          duration: '20 min',
          channel: 'Butterfly Spanish',
          status: 'in_progress',
          favorite: false,
          bookmarked: true,
          tags: ['verbs'],
          note: '',
        },
        {
          id: 'l-es-2',
          title: 'Ser and estar',
          url: 'https://www.youtube.com/watch?v=QGe6sYy2cs4',
          duration: '13 min',
          channel: 'Butterfly Spanish',
          status: 'not_started',
          favorite: true,
          bookmarked: false,
          tags: ['grammar'],
          note: '',
        },
      ],
    },
  ],
  tasks: [
    {
      id: 'task-1',
      title: 'Finish card-state exercise',
      subjectId: 'design',
      due: '2026-10-24T09:00',
      kind: 'assignment',
      priority: 'high',
      done: true,
    },
    {
      id: 'task-2',
      title: 'Design systems checkpoint',
      subjectId: 'design',
      due: '2026-10-26T11:00',
      kind: 'exam',
      priority: 'high',
      done: false,
    },
    {
      id: 'task-3',
      title: 'Gradient descent retrieval practice',
      subjectId: 'ml',
      due: '2026-10-24T14:00',
      kind: 'revision',
      priority: 'medium',
      done: false,
    },
    {
      id: 'task-4',
      title: 'Verb practice',
      subjectId: 'spanish',
      due: '2026-10-24T18:30',
      kind: 'revision',
      priority: 'low',
      done: false,
    },
  ],
  notes: [
    {
      id: 'note-1',
      title: 'Typography systems',
      subjectId: 'design',
      updatedAt: '2026-10-24T09:15:00',
      body: '# Typography systems\n\nA useful scale makes the interface feel intentional.\n\n## Remember\n\n- Use **one** clear hierarchy\n- Let spacing do some of the work\n- Test at small sizes\n\n> Good typography is quiet confidence.',
    },
    {
      id: 'note-2',
      title: 'Gradient descent intuition',
      subjectId: 'ml',
      updatedAt: '2026-10-22T16:15:00',
      body: '# Gradient descent\n\nMove in the direction that reduces loss. Start with a learning rate that is small enough to be stable.',
    },
  ],
  goals: [
    { id: 'goal-1', title: 'Focused minutes this week', target: 480, current: 390, unit: 'min' },
    { id: 'goal-2', title: 'Complete design system', target: 18, current: 13, unit: 'lessons' },
  ],
  activity: [
    { id: 'a-1', label: 'Completed “Components that scale”', time: 'Today, 09:20', category: 'study' },
    { id: 'a-2', label: 'Updated Typography systems note', time: 'Today, 09:15', category: 'note' },
    { id: 'a-3', label: 'Marked a checkpoint as upcoming', time: 'Yesterday', category: 'task' },
  ],
  dailyGoalMinutes: 60,
  studiedTodayMinutes: 45,
  language: 'en',
};
